import Head from "next/head";
import React from "react";
import Headers from "@/components/headers";
import fotoku3 from "../assets/image/fotoku3.jpg";
import Image from "next/image";

const About = () => {
  return (
    <>
      <Head>
        <title>My Portofolio | About </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <Headers />
        <div className="relative top-24 flex justify-center transition-all">
          <div className="sm:relative sm:left-10">
            <div className="flex justify-center">
              <Image
                width={300}
                height={0}
                className="rounded-full"
                src="/assets/image/fotoku3.jpg"
                alt="fotoku3"
              />
            </div>
            <div className="mt-5">
              <p className="text-xl font-semibold font-SourceSansPro text-center">
                Hi, i{`'`}m Zaki, nice to meet you !
              </p>
              <p className="text-md text-center italic mt-5 w-128 sm:w-72 md:w-[35rem] pb-5">
                {`"`}I am a bachelor degree of Informatics Engineering from
                University of Muhammadiyah Malang. Experienced as a Front-End
                Developer who works with HTML, CSS, JavaScript, React.js, Redux,
                TailwindCss, Bootstrap, and Rest API. Have a high interest in
                the field of web development, especially front-end developer.
                Attended the Kampus Merdeka program with the front-end
                JavaScript program at Binar Academy. A detail-oriented
                individual who is eager for a full-time opportunity in Front-end
                Web Development{`"`}
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default About;
