import Head from 'next/head'
import Headers from '../components/headers'
import React from 'react'
import CardContact from '@/components/CardContact'

const Contact = () => {
  return (
    <>
        <Head>
            <title>My Portofolio | My Contact </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <Headers />
            <div className='flex justify-center mt-32'>
                <CardContact />
            </div>
        </main>
    </>
  )
}


export default Contact