import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import Headers from "@/components/Headers";
import fotoku from "../assets/image/fotoku.png";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>My Portfolio | Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <Headers />
        <div className="relative top-32 ml-16 sm:left-5 md:left-0 sm:ml-0 md:ml-16">
          <div className="flex">
            <div className="flex-initial w-8/12 sm:w-full md:w-8/12 mt-28">
              <p className="text-black text-5xl sm:ml-14 md:ml-0 sm:text-center md:text-start font-lilitaOne">
                Hi, My Name{" "}
                <span className="text-green-600">Muhammad Zaki Kurniawan</span>
              </p>
              <p
                id="typing"
                className="text-black text-6xl sm:text-4xl md:text-6xl font-lilitaOne pt-5 overflow-hidden whitespace-nowrap"
              >
                I{`'`}m{" "}
                <span className="text-green-600">Frontend Developer</span>
              </p>
              <div id="line">|</div>
            </div>
            <div className="flex-initial w-72 sm:sr-only md:not-sr-only">
              <div className="relative ml-20">
                <img width="214" src={fotoku.src} alt="fotoku" />
                <span className="absolute bottom-20 -z-10 left-2/4 -translate-x-2/4">
                  <svg width="400" height="400" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
                    <path
                      fill="#24A148"
                      d="M67.5,-20.4C77.2,7.8,67.5,43.7,43.6,61.4C19.7,79.1,-18.5,78.5,-42.5,60.6C-66.5,42.6,-76.3,7.3,-66.8,-20.5C-57.4,-48.3,-28.7,-68.7,0.1,-68.7C28.9,-68.8,57.9,-48.5,67.5,-20.4Z"
                      transform="translate(100 100) scale(1.2)"
                    />
                  </svg>
                </span>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
